### ISSUE TITLE
请问一下唐老师书里面像下面这种流程图是用什么软件画出来的呢？

### ISSUE THREAD

**Issue by zonnin** [GenTang/intro_ds#1]
请问一下唐老师书里面像下面这种流程图是用什么软件画出来的呢？

![_20180527151537](https://user-images.githubusercontent.com/605128/40583425-e559d1e2-61c0-11e8-89c0-5aac1b67aeb4.jpg)

不胜感激，谢谢！

**Comment by GenTang** [comment]
您好。

书中的图都是用mac自带的Keynote画出来的。本来是有颜色的，可惜只能印黑白书。
谢谢

祝好
亘

**Comment by zonnin** [comment]
非常感谢！刚开始看《精通数据科学》，感觉这是一本很用心制作的书，祝唐老师新书大卖！

**Comment by GenTang** [comment]
哈哈，谢谢您的肯定😄
