### ISSUE TITLE
建议可以用jupyter notebook发布图文并茂的课程

### ISSUE THREAD

**Issue by Wilson-G** [GenTang/intro_ds#6]
从csdn过来，非常感谢辛劳和无私的付出，看到这个repo都是源码，不如选择使用notebook来发布课程，这样可以方便学员快速运行代码和看到效果

**Comment by GenTang** [comment]
多谢你的建议，我研究一下。jupyter我还没有用过

**Comment by GenTang** [comment]
第一次使用，效果还不错。果然清晰了不少。

https://github.com/GenTang/intro_ds_wy_course/blob/master/ch05_logit/code/logit_example.ipynb

**Comment by Wilson-G** [comment]
👍
